name: Amazon CodeGuru Reviewer

on:
  #   push:
  #     branches: [main]
  pull_request:
    branches: [main]

jobs:
  codeguru-review:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"

      #   - name: Build with Maven
      #     run: mvn clean package -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run Amazon CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@v1.1
        with:
          build_path: target
          s3_bucket: ${{ secrets.AWS_CODEGURU_REVIEWER_S3_BUCKET }}

      - name: Upload SARIF results
        if: ${{ github.event_name != 'push' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeguru-results.sarif.json
